language: ruby
before_install:
  - gem install bundler
  - gem install kramdown
  - gem install therubyracer
  - gem install jekyll 
  - gem install jekyll-less 
  - gem install jekyll-press 
script: jekyll build
rvm:
  - 1.9.3
