language: ruby

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
  allow_failures:
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ruby    ; fi

install: bundle install
script: bundle exec jekyll build -d _site && bundle exec htmlproofer ./_site/

rvm:
  - 2.3.1
  - 2.5.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
notifications:
  email: false
