language: ruby
sudo: false
install: bundle install
script: bundle exec jekyll build -d _site && bundle exec htmlproofer ./_site/
rvm:
  - 2.3.1
  - 2.5.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
notifications:
  email: false
