# Site settings
title: OpenPGP Public Key Server
email: matt@mattrude.com
description: ""
baseurl: ""
url: "http://keyserver.mattrude.com"
destination: "/var/www/keyserver.mattrude.com"

# Analytics settings
#google_analytics_id: UA-55622044-1

# Build settings
markdown: kramdown
permalink: pretty

exclude:
- README.md

gems:
- jekyll-sitemap
- jekyll-less
- jekyll-press
- jekyll-last-modified-at
