# Site settings
title: OpenPGP Public SKS Key Server
email: matt@mattrude.com
description: ""
baseurl: ""
url: "http://keyserver.mattrude.com"
destination: "/var/www/keyserver.mattrude.com"

# Analytics settings
#gauges_id: 
#google_analytics_id: 

# Build settings
markdown: kramdown
permalink: pretty

exclude:
- README.md

gems:
- jekyll-sitemap
- jekyll-less
- jekyll-press
- jekyll-last-modified-at
