# Site settings
title: OpenPGP Public Key Server
email: matt@mattrude.com
description: ""
url: "http://keyserver.mattrude.com"
baseurl: "keyserver.mattrude.com"
destination: "/var/www/keyserver.mattrude.com"

# Analytics settings
#google_analytics_id: UA-55622044-1

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

exclude:
- README.md

gems:
- jekyll-sitemap
- jekyll-less
- jekyll-press
- jekyll-last-modified-at

jekyll-press:
  exclude: 'robots.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
