# Site settings
title: PGP Public Keyserver
email: matt@mattrude.com
description: ""
url: "//keyserver.mattrude.com"
name: "keyserver.mattrude.com"
baseurl: ""
destination: "/var/www/keyserver.mattrude.com"

owner_name: "Matt Rude"
owner_pgpkey: "0xc4909ee495b0761f"
owner_omemo: "a4b88aca f63e1f05 6f8fd700 7847baf3 3f653098 64d478a7 d7387c88 fd8fb834"
owner_github: "mattrude"
owner_twitter: "mdrude"
owner_facebook: "mattrude"
owner_instagram: "mattdrude"
owner_website: "https://mattrude.com"

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /changelog/:year-:month-:day-:title/
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- Gemfile
- Gemfile.lock
- README.md
- CONTRIBUTING.md
- LICENSE
- css/syntax.less
- css/site.less
- css/small.less

gems:
- jekyll-sitemap
#- jekyll-less
- jekyll-press
- jekyll-redirect-from
- jekyll-last-modified-at

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
