# Site settings
title: OpenPGP Keyserver
email: matt@mattrude.com
description: ""
url: "https://a.sks.jda.mn"
name: "a.sks.jda.mn"
baseurl: ""

owner_name: "Jonah Aragon"
owner_email: "jonah@triplebit.net"
owner_keybase: "jonaharagon"
owner_xmpp: ""
owner_pgpkey: "0xDB49BB255B868219"
owner_omemo: ""
owner_github: "jonaharagon"
owner_twitter: "jonaharagon"
owner_facebook: ""
owner_instagram: "jonaharagon"
owner_website: "https://jda.mn"

# Analytics settings
google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /changelog/:year-:month-:day-:title/
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- Gemfile
- Gemfile.lock
- README.md
- CONTRIBUTING.md
- LICENSE
- css/syntax.less
- css/site.less
- css/small.less

plugins:
#- jekyll-press
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-last-modified-at

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
